name: talent-lms-integration
channels:
- conda-forge
- defaults
dependencies:
- python
- pandas
- seaborn # data viz
- statsmodels
- scikit-learn
- scipy
- altair # data viz
- google-cloud-bigquery
- ipykernel # to show the kernel on jupyter
- pandas-profiling
- pandas-gbq
- google-cloud-storage
- fsspec # to use pandas with gcs
- gcsfs # to use pandas with gcs